version: "3.7"

services:

  nginx:
    restart: always
    build:
      target: nginx_production
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TYPE: advanced # advanced or basic
        # basic is without hasura and keycloak

    depends_on:
      - razzle

    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:?Host required}

  razzle:
    restart: always
    build:
      target: razzle_production
      context: .
      dockerfile: Dockerfile

    environment:
      PUBLIC_HOST: ${VIRTUAL_HOST:?Host required}
      PUBLIC_SCHEME: https
