version: "3.7"

services:

  razzle:
    restart: always
    build:
      target: razzle_production
      context: .
      dockerfile: Dockerfile

    environment:
      PUBLIC_HOST: ${VIRTUAL_HOST:?Host required}
      PUBLIC_SCHEME: https
      VIRTUAL_HOST: https://${VIRTUAL_HOST:?Host required} -> :3000
