version: "3.7"

services:
  nginx-proxy:
    image: nginx-proxy
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - ${CERTS_VOLUME}:/etc/nginx/certs:ro
      - ${VHOST_D_VOLUME}:/etc/nginx/vhost.d
      - ${HTML_VOLUME}:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-letsencrypt:
    image: nginx-proxy-letsencrypt
    volumes:
      - ${CERTS_VOLUME}:/etc/nginx/certs:ro
      - ${VHOST_D_VOLUME}:/etc/nginx/vhost.d
      - ${HTML_VOLUME}:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}