version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
     - "80:80"
    command: /bin/sh -c "envsubst '$${NGINX_SERVER_NAME},$${RAZZLE_CONTAINER_HOST},$${WEBPACK_PORT},$${EXPRESS_PORT}' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/nginx.template
    environment:
      RAZZLE_CONTAINER_HOST: ${RAZZLE_CONTAINER_HOST:-razzle}
      EXPRESS_PORT: ${EXPRESS_PORT:-3000}
      WEBPACK_PORT: ${WEBPACK_PORT:-3001}
      NGINX_SERVER_NAME: ${RAZZLE_PUBLIC_HOST:-localhost}

  razzle:
    build:
      target: dev
      context: .
      dockerfile: Dockerfile
    image: razzleapp:latest
    expose:
      - ${EXPRESS_PORT:-3000}
      - ${WEBPACK_PORT:-3001}
    volumes:
      - ./src:/code/src
      - ./public:/code/public
      - ./razzle.config.js:/code/razzle.config.js
    environment:
      PORT: ${EXPRESS_PORT:-3000}
      PUBLIC_PATH: ${RAZZLE_PUBLIC_SCHEME:-http}://${RAZZLE_PUBLIC_HOST:-localhost}:${RAZZLE_PUBLIC_PORT:-80}/webpack/
      CLIENT_PUBLIC_PATH: ${RAZZLE_PUBLIC_SCHEME:-http}://${RAZZLE_PUBLIC_HOST:-localhost}:${RAZZLE_PUBLIC_PORT:-80}/webpack/
      RAZZLE_PUBLIC_HOST: ${RAZZLE_PUBLIC_HOST:-localhost}
      RAZZLE_PUBLIC_PORT: ${RAZZLE_PUBLIC_PORT:-80}