version: "3.7"

services:
  nginx-proxy:
    restart: always
    image: mesudip/nginx-proxy
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - ${SSL_VOLUME_PATH:-ssl}:/etc/ssl
      - nginx:/etc/nginx
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  ssl:
    external:
      name: ${SSL_VOLUME}
  nginx:
    external:
      name: ${NGINX_VOLUME}
