version: "3.7"

services:

  nginx:
    build:
      target: nginx_development
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TYPE: advanced # advanced or basic
        # basic is without hasura and keycloak

    depends_on:
      - razzle

    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:-localhost}

  razzle:
    build:
      target: razzle_development
      context: .
      dockerfile: Dockerfile

    environment:
      PUBLIC_HOST: ${VIRTUAL_HOST:-localhost}
      PUBLIC_PORT: ${PUBLIC_PORT:-}
      PUBLIC_SCHEME: ${PUBLIC_SCHEME:-https}
      RAZZLE_DEV: "true"

    volumes:
      - ./razzle/src:/code/src
      - ./razzle/public:/code/public
      - ./razzle/razzle.config.js:/code/razzle.config.js
      # - ./razzle/.babelrc:/code/.babelrc
      # - ./razzle/.eslintrc.js:/code/.eslintrc.js
